### ISSUE TITLE
Predict negative number

### ISSUE THREAD

**Issue by dbof10** [fasiha/ebisu-java#3]
On your readme, the second line return -0.69.... What do we do with negative number?
```jshell> double timeElapsed = 0.25; // you figure this out based on a timestamp
timeElapsed ==> 0.25

jshell> double logRecallProbability = Ebisu.predictRecall(model1, timeElapsed);
logRecallProbability ==> -0.6931471805599458

jshell> double recallProbability = Ebisu.predictRecall(model1, timeElapsed, true);
recallProbability ==> 0.4999999999999997
```

**Comment by fasiha** [comment]
The negative number is a log-probability, which is the default return because to convert to real probability requires Math.exp, which is expensive compared to arithmetic. You can still sort log-probabilities just like regular probabilities though! The only reason I can imagine passing in the argument for exact probability is for displaying to a human.
