### ISSUE TITLE
updateRecall api usage

### ISSUE THREAD

**Issue by dbof10** [fasiha/ebisu-java#4]
My implementation is when a student learns a fact, I construct an Ebisu model. After t amount of time, I would call

`var predictedRecall = ebisu.predictRecall(model, elapsed, true);` elapsed here is computed by `currenttime - ebisu created timestamp`. This seems very straightforward. When it drops below threshold, I convert a fact into a quiz.

With updateRecall api

it requires an elapsed time. Based on your docs it is `ebisu.updateRecall(model, result, tnow) -> model to update the model given a quiz result and time after its last review.` what do you mean `last review time`? is it the same as `createTimestamp` when I constructor Ebisu model? Given it's a different timestamp, I will call it reviewTimestamp, when user reviews a fact, I create reviewTimestamp, after a minute he takes a quiz, elapsed would be = 0.1 in this case, my question is what is the value for `elapsed` if user doesn't review since he learned a fact?

**Comment by fasiha** [comment]
> what do you mean last review time? is it the same as createTimestamp when I constructor Ebisu model?

Yes, this part is right, but don’t create a reviewTimestamp the way you’re thinking. It’s important to remember that updateRecall returns a **new** Ebisu model just like the constructor. So have a *single* timestamp for when a model is created by *either* of these methods (that is, immediately after first learning and after a review).

So your quiz app will do the following:
- user learns flash card: `model = new EbisuModel(...); timestamp = new Time();` and store these two in database.
- user wants to review. `elapsed = new Time() - timestamp; predictRecall(model, elapsed);`
- user finishes review after a minute: `now = new Time(); elapsed = now - timestamp; model = Ebisu.updateRecall(model, result, elapsed); timestamp = now;` and update these two in your database (overwriting old values)
- user reviews the flash card a day later, exact same thing: `now = new Time(); elapsed = now - timestamp;` etc., overwrite `model` and `timestamp` in database.

Does that make sense?

Another way to think about it is, predictRecall and updateRecall have to know how long it’s been since the user last saw the flashcard.

**Comment by dbof10** [comment]
Currently, what I am doing is I have createTimestamp and reviewTimestamp
after a quiz, if user reviews beforehand, `updateModel` with elapse = now - reviewTimestamp
else (no review case) else `updateModel` with elapse = now - createTimestamp.

I think it sounds ok to me but I need your input on this

**Comment by fasiha** [comment]
So then you have to keep track of whether the user has ever reviewed this flash card to know which timestamp to use? I think that should work but that seems over-complicated to me since you don’t need two timestamps, you can use a single one that corresponds to the creation time of the model object, whether after first learned or after quiz (recall updateModel creates a new EbisuModel object).

If you want to keep track of when the user first learned the flash card for display purposes or whatever, keep createTimestamp but don’t use it for predict/updateRecall, use a separate timestamp that always corresponds to the creation time of the model object.

I’ll try to think on how to make this more straightforward, since it’s confusing.

**Comment by dbof10** [comment]
I figured out how to combine reviewTimestamp to createTimestamp

**Comment by dbof10** [comment]
Like you said above after review I called, user just reviews a fact
```Ebisu.updateRecall(model, result, elapsed)``` . Result is a boolean. What is the value you should feed here? true or false?

Also
After a quiz, I also call ```Ebisu.updateRecall(model, result, elapsed)``` with result is the result of the quiz? Is that correct?

**Comment by fasiha** [comment]
> Like you said above after review I called, user just reviews a fact
> `Ebisu.updateRecall(model, result, elapsed)` . Result is a boolean. What is the value you should feed here? true or false?

It's not clear to me if here you mean when you first learn the fact, or after quiz review?

If you've just learned a fact, set the model of that flashcard to `new EbisuModel(initialHalflife, 2, 2);` (or whatever `alpha=beta` value you like).

Then after you have the result of a quiz, you replace the flashcard's model with the output of `Ebisu.updateRecall(model, result, elapsed)` where `result=true` if the quiz is a success, and `result=false` if the quiz was a failure.

Does that make sense? The Python repo has a [IPython Notebook](https://github.com/fasiha/ebisu/blob/gh-pages/EbisuHowto.ipynb) that shows how the API is used.

**Comment by dbof10** [comment]
> * ng old values)


```user finishes review after a minute: now = new Time(); elapsed = now - timestamp; model = Ebisu.updateRecall(model, result, elapsed); timestamp = now; and update these two in your database (overwriting old values)```

As you said here, what do you mean review in this context? My review means use open a fact that he learnt and read again, no quiz here. What shud we do in this case, because updateModel api doesnt work in this context

**Comment by fasiha** [comment]
Ahh, thank you for explaining, I now see: rather than a quiz with *active* recall, the user just reviewed the fact *passively*. In that situation, keep the existing model, and just change the `timestamp` to now 😎!

---

In code:

(1) **active** review where the user passes or fails a quiz:
```
// given `timestamp` and `model` and `result`:
var now = new Time();
var elapsed = now - timestamp;
model = Ebisu.updateRecall(model, result, elapsed);
timestamp = now;
```

In contrast, (2) **passive** review with no true/false quiz:
```
// given `timestamp` and `model`:
// no change to model!
timestamp = new Time();
```

---

(The reason this works is, the `model` encodes your belief about the memory's probability distribution as of `timestamp`; that memory model decays as time passes, and only gets updated when the user *actively* tries to recall it. If the user *passively* reviewed the fact, then you still have the exact same model for their memory; you just update the timestamp and reset the decay.)

---

So as you can see here, I use the words "active" and "passive" to denote these two separate kinds of reviews. Is there a better way to phrase these? The Ebisu API doesn't really provide a function for passive reviews since Ebisu doesn't do any calculations in that case: a passive review is just handled by the quiz app itself, without involving Ebisu.

Maybe I can update the docstring for `updateRecall` to explain this further, something like:
```
Caveat: only call `updateRecall` when you have a quiz that produced a true/false result!
If the fact was passively reviewed and didn't produce true/false result, reuse the same model,
and update its timestamp to the time of the review.
```
What do you think?

**Comment by dbof10** [comment]
After discussion, it's clear to me. If user just review the fact, we just update model with new timestamp,
If they do the quiz, use updateRecall api.
Thanks for the explanation
